apiVersion: v2
name: rqlite
version: 1.15.1
appVersion: 8.36.11
description: The lightweight, distributed relational database built on SQLite
type: application
home: https://rqlite.io/
keywords:
  - rqlite
  - sqlite
  - sql
  - database
  - distributed
annotations:
  artifacthub.io/category: database
  artifacthub.io/license: MIT
sources:
  - https://github.com/rqlite/
  - https://github.com/rqlite/rqlite
  - https://github.com/rqlite/helm-charts
maintainers:
  - name: jtackaberry
